### GET request to example server
GET http://localhost:8080/api/libros
Accept: application/json

### GET request with id
GET http://localhost:8080/api/libros/9788432202391
Accept: application/json

### Crear un nuevo libro
POST http://localhost:8080/api/libros
Content-Type: application/json

{
  "isbn": "9780394172422",
  "titulo": "El laberinto de la soledad",
  "numPag": 444,
  "editorial": {
    "id": "E004"
  }
}

###