### GET request to example server
GET http://localhost:8080/api/libros
Accept: application/json

### GET request with id
GET http://localhost:8080/api/libros/9788432202391
Accept: application/json

### Crear un nuevo libro
POST http://localhost:8080/api/libros
Content-Type: application/json

{
  "isbn": "9780394172422",
  "titulo": "El laberinto de la soledad",
  "numPag": 444,
  "editorial": {
    "id": "E004"
  }
}

### POST para ejemplar
POST http://localhost:8080/api/ejemplares
Content-Type: application/json

{
  "id": "EJ009",
  "ubicacion" : "Estante B3",
  "estado": true,
  "libro": {
    "isbn": "9780394172422"
  }
}

### GET para miembros
GET http://localhost:8080/api/miembro
Accept: application/json

###GET para miembros por id
GET http://localhost:8080/api/miembro/M005
Accept: application/json

### POST creacion de miembro
POST http://localhost:8080/api/miembro
Content-Type: application/json

{
  "idMiembro": "M006",
  "nombre": "Emilio",
  "apellido": "Cardona",
  "correo": "CardonaEmilio@correo.com",
  "direccion": "CLL34AA#21-10",
  "telefono": "3216745321"
}

### POST duplicado en miembro
POST http://localhost:8080/api/miembro
Content-Type: application/json

{
  "idMiembro": "M006",
  "nombre": "Emilio",
  "apellido": "Cardona",
  "correo": "CardonaEmilio@correo.com",
  "direccion": "CLL34AA#21-10",
  "telefono": "3216745321"
}

###PUT actualizacaion
PUT http://localhost:8080/api/miembro/M006
Content-Type: application/json

{
  "nombre": "Emilio",
  "apellido": "Jaramillo",
  "correo": "CardonaEmilio@correo.com",
  "direccion": "CLL34AA#21-10",
  "telefono": "3216745324"
}

###POST Miembro
POST http://localhost:8080/api/miembro
Content-Type: application/json

{
    "idMiembro": "M007",
    "nombre": "Carlitos",
    "apellido": "Garcia",
    "telefono": "3003009871",
    "correo": "GarciaCarlos@correo.com",
    "direccion": "CLL 12AA #44BB -33"
}

###PUT miembro
PUT http://localhost:8080/api/miembro/M007
Content-Type: application/json

{
  "apellido": "Castro"
}


